#!/usr/bin/env node
/*
 * Downloads stroke-order data for every character used in data/vocabulary.js
 * and writes data/strokes.js (window.STROKES = { "爱": {...}, ... }).
 *
 * Usage:
 *   node scripts/convert.js        # first, if vocabulary.txt changed
 *   node scripts/fetch-strokes.js
 *
 * Needs Node 18+ (built-in fetch) and an internet connection, once.
 * Data: hanzi-writer-data (derived from Make Me a Hanzi), Arphic Public License.
 * See vendor/ARPHICPL.txt and vendor/COPYING-stroke-data.md.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const VOCAB = path.join(ROOT, 'data', 'vocabulary.js');
const OUT = path.join(ROOT, 'data', 'strokes.js');
const DATA_VERSION = '2.0.1';
const BASE_URL = `https://cdn.jsdelivr.net/npm/hanzi-writer-data@${DATA_VERSION}/`;
const CONCURRENCY = 12;

function loadVocabulary() {
  if (!fs.existsSync(VOCAB)) {
    console.error('data/vocabulary.js not found. Run: node scripts/convert.js');
    process.exit(1);
  }
  const sandbox = { window: {} };
  vm.runInNewContext(fs.readFileSync(VOCAB, 'utf8'), sandbox);
  return sandbox.window.VOCABULARY;
}

/** Every character that can be written: main form, variants and examples. */
function collectChars(words) {
  const chars = new Set();
  for (const w of words) {
    const forms = [w.hanzi].concat(
      w.variants.map((v) => v.hanzi),
      w.example ? [w.example.hanzi] : []
    );
    for (const form of forms) {
      for (const ch of Array.from(form)) {
        if (/\p{Script=Han}|〇/u.test(ch)) chars.add(ch);
      }
    }
  }
  return Array.from(chars).sort();
}

async function fetchChar(ch) {
  const res = await fetch(BASE_URL + encodeURIComponent(ch) + '.json');
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`${ch}: HTTP ${res.status}`);
  const data = await res.json();
  // Keep only what Hanzi Writer needs.
  return { strokes: data.strokes, medians: data.medians, radStrokes: data.radStrokes };
}

async function main() {
  if (typeof fetch !== 'function') {
    console.error('This script needs Node 18 or newer (built-in fetch).');
    process.exit(1);
  }

  const chars = collectChars(loadVocabulary());
  console.log(`Fetching stroke data for ${chars.length} characters...`);

  const result = {};
  const missing = [];
  let next = 0;

  async function worker() {
    while (next < chars.length) {
      const ch = chars[next++];
      let data = null;
      for (let attempt = 1; attempt <= 3; attempt++) {
        try {
          data = await fetchChar(ch);
          break;
        } catch (err) {
          if (attempt === 3) throw err;
        }
      }
      if (data) result[ch] = data;
      else missing.push(ch);
    }
  }

  await Promise.all(Array.from({ length: CONCURRENCY }, worker));

  const sorted = {};
  Object.keys(result).sort().forEach((ch) => {
    sorted[ch] = result[ch];
  });

  const js =
    '/* Generated by scripts/fetch-strokes.js. Do not edit by hand.\n' +
    ` * Stroke data: hanzi-writer-data@${DATA_VERSION} (Make Me a Hanzi), Arphic Public License.\n` +
    ' * See vendor/ARPHICPL.txt and vendor/COPYING-stroke-data.md. */\n' +
    'window.STROKES = {\n' +
    Object.keys(sorted)
      .map((ch) => '  ' + JSON.stringify(ch) + ': ' + JSON.stringify(sorted[ch]))
      .join(',\n') +
    '\n};\n';

  fs.writeFileSync(OUT, js, 'utf8');
  const kb = Math.round(Buffer.byteLength(js) / 1024);
  console.log(`Wrote data/strokes.js (${Object.keys(sorted).length} characters, ${kb} KB)`);
  if (missing.length) console.log(`No stroke data for: ${missing.join(' ')}`);
}

main().catch((err) => {
  console.error('Failed: ' + err.message);
  process.exit(1);
});
